### ISSUE TITLE
Feature Request: Support for external-dns annotations

### ISSUE THREAD

**Issue by ohauer** [Ragin-LundF/k8s-jcasc-management-go#29]
add support for multiple annotations for the service e,g.

```
metadata:
  name: echo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: echo.k8s.example.com, echo.devops.example.com
    external-dns.alpha.kubernetes.io/ttl: "60"
```
